version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build

permissions:
  - object: /home/ubuntu/build
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180
