spring:
  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        # show_sql: true
        format_sql: true

    h2:
      console:
        enabled: true
        path: /h2-console

  datasource:
    url: jdbc:h2:mem://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080
#  error:
#    include-stacktrace: never
#    include-message: never
#    include-binding-errors: never

logging.level:
  org.hibernate.SQL: debug


  # org.hibernate.type: trace
  #  spring.resources.static-locations=classpath:/static/
  #  spring.resources.add-mappings=true
  #  spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.ddl-auto=none
#  spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.properties.hibernate.globally_quoted_identifiers=true
#  spring.datasource.url=jdbc:mysql://localhost:3306/woorder?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#  spring.datasource.username=root
#  spring.datasource.password=1234
logging:
  level:
    org:
      springframework:
        web: debug
