af: "아프가니스탄"
ax: "올란드 제도"
al: "알바니아"
dz: "알제리"
as: "아메리칸 사모아"
ad: "안도라"
ao: "앙골라"
ai: "앵귈라"
aq: "남극"
ag: "앤티가 바부다"
ar: "아르헨티나"
am: "아르메니아"
aw: "아루바"
au: "호주"
at: "오스트리아"
az: "아제르바이잔"
bs: "바하마"
bh: "바레인"
bd: "방글라데시"
bb: "바베이도스"
by: "벨라루스"
be: "벨기에"
bz: "벨리즈"
bj: "베냉"
bm: "버뮤다"
bt: "부탄"
bo: "볼리비아"
ba: "보스니아 헤르체고비나"
bw: "보츠와나"
bv: "부베 섬"
br: "브라질"
io: "영국령 인도양 지역"
bn: "브루나이"
bg: "불가리아"
bf: "부르키나파소"
bi: "부룬디"
kh: "캄보디아"
cm: "카메룬"
ca: "캐나다"
cv: "카보베르데"
ky: "케이맨 제도"
cf: "중앙 아프리카 공화국"
td: "차드"
cl: "칠레"
cn: "중국"
cx: "크리스마스 섬"
cc: "코코스 제도"
co: "콜롬비아"
km: "코모로"
cg: "콩고"
cd: "콩고 민주 공화국"
ck: "쿡 제도"
cr: "코스타리카"
ci: "코트디부아르"
hr: "크로아티아"
cu: "쿠바"
cy: "키프로스"
cz: "체코"
dk: "덴마크"
dj: "지부티"
dm: "도미니카"
do: "도미니카 공화국"
ec: "에콰도르"
eg: "이집트"
sv: "엘살바도르"
gq: "적도 기니"
er: "에리트레아"
ee: "에스토니아"
et: "에티오피아"
fk: "포클랜드 제도"
fo: "페로 제도"
fj: "피지"
fi: "핀란드"
fr: "프랑스"
gf: "프랑스령 기아나"
pf: "프랑스령 폴리네시아"
tf: "프랑스 남부 지방"
ga: "가봉"
gm: "감비아"
ge: "조지아"
de: "독일"
gh: "가나"
gi: "지브롤터"
gr: "그리스"
gl: "그린란드"
gd: "그레나다"
gp: "과들루프"
gu: "괌"
gt: "과테말라"
gg: "건지"
gn: "기니"
gw: "기니비사우"
gy: "가이아나"
ht: "하이티"
hm: "허드 맥도널드 제도"
va: "바티칸"
hn: "온두라스"
hk: "홍콩"
hu: "헝가리"
is: "아이슬란드"
in: "인도"
id: "인도네시아"
ir: "이란"
iq: "이라크"
ie: "아일랜드"
im: "맨섬"
il: "이스라엘"
it: "이탈리아"
jm: "자메이카"
jp: "일본"
je: "저지"
jo: "요르단"
kz: "카자흐스탄"
ke: "케냐"
ki: "키리바시"
kp: "북한"
kr: "한국"
kw: "쿠웨이트"
kg: "키르기스스탄"
la: "라오스"
lv: "라트비아"
lb: "레바논"
ls: "레소토"
lr: "라이베리아"
ly: "리비아"
li: "리히텐슈타인"
lt: "리투아니아"
lu: "룩셈부르크"
mo: "마카오"
mk: "북마케도니아"
mg: "마다가스카르"
mw: "말라위"
my: "말레이시아"
mv: "몰디브"
ml: "말리"
mt: "말타"
mh: "마셜 제도"
mq: "마르티니크"
mr: "모리타니"
mu: "모리셔스"
yt: "마요트"
mx: "멕시코"
fm: "미크로네시아"
md: "몰도바"
mc: "모나코"
mn: "몽골"
me: "몬테네그로"
ms: "몬트세라트"
ma: "모로코"
mz: "모잠비크"
mm: "미얀마"
na: "나미비아"
nr: "나우루"
np: "네팔"
nl: "네덜란드"
an: "네덜란드령 안틸레스"
nc: "뉴칼레도니아"
nz: "뉴질랜드"
ni: "니카라과"
ne: "니제르"
ng: "나이지리아"
nu: "니우에"
nf: "노퍽 섬"
mp: "북마리아나 제도"
no: "노르웨이"
om: "오만"
pk: "파키스탄"
pw: "팔라우"
ps: "팔레스타인"
pa: "파나마"
pg: "파푸아뉴기니"
py: "파라과이"
pe: "페루"
ph: "필리핀"
pn: "핏케언 제도"
pl: "폴란드"
pt: "포르투갈"
pr: "푸에르토리코"
qa: "카타르"
re: "레위니옹"
ro: "루마니아"
ru: "러시아"
rw: "르완다"
bl: "생바르텔레미"
sh: "세인트헬레나"
kn: "세인트키츠 네비스"
lc: "세인트루시아"
mf: "세인트마틴"
pm: "세인트피에르 미클롱"
vc: "세인트빈센트 그레나딘스"
ws: "사모아"
sm: "산마리노"
st: "상투메 프린시페"
sa: "사우디아라비아"
sn: "세네갈"
rs: "세르비아"
sc: "세이셸"
sl: "시에라리온"
sg: "싱가포르"
sk: "슬로바키아"
si: "슬로베니아"
sb: "솔로몬 제도"
so: "소말리아"
za: "남아프리카"
gs: "남조지아 사우스샌드위치 제도"
es: "스페인"
lk: "스리랑카"
sd: "수단"
sr: "수리남"
sj: "스발바르 얀마옌 제도"
sz: "스와질랜드"
se: "스웨덴"
ch: "스위스"
sy: "시리아"
tw: "대만"
tj: "타지키스탄"
tz: "탄자니아"
th: "태국"
tl: "동티모르"
tg: "토고"
tk: "토켈라우"
to: "통가"
tt: "트리니다드 토바고"
tn: "튀니지"
tr: "터키"
tm: "투르크메니스탄"
tc: "터크스 케이커스 제도"
tv: "투발루"
ug: "우간다"
ua: "우크라이나"
ae: "아랍에미리트"
gb: "영국"
us: "미국"
um: "미국령 군소 제도"
uy: "우루과이"
uz: "우즈베키스탄"
vu: "바누아투"
va: "바티칸"
ve: "베네주엘라"
vn: "베트남"
vg: "영국령 버진 제도"
vi: "미국령 버진 제도"
wf: "왈리스 퓌튀나"
eh: "서사하라"
ye: "예멘"
zm: "잠비아"
zw: "짐바브웨"
