spring:
  config:
    activate:
      on-profile: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:mysql://test.cucwjkdfizin.ap-northeast-2.rds.amazonaws.com:3306/lingoswap?useSSL=false
    username: soma1454
    password: DEpGf4lGQ5cc6YHPW

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /lingo/swap
      exposure:
        include: health

  endpoint.health.enabled: true

server:
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never

logging.level:
  org.hibernate.SQL: debug

sendbird:
  api-url: https://api-DC52A85B-A985-4651-AF95-737C9A26CEDD.sendbird.com/v3
  api-token: 58f272aed37a9b0224eec5736783337ab5b2f2a4

aws:
  credentials:
    access-key: AKIAUE27WOA6LTISR3AP
    secret-key: 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
  region:
    static: ap-northeast-2
