name: cd-main
on:
  workflow_run:
    workflows: [ ci ]
    branches:
      - main
    types:
      - completed

env:
  BUCKET_NAME: lingotalk-build
  ARN: arn:aws:iam::455541718696:role/GithubActionsForCodeDeploy
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'semeru'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Compress build files
        run: |
          zip -r -qq -j ./build.zip ./build/libs/*.jar ./appspec.yml ./execute-deploy.sh

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./build.zip s3://${{ env.BUCKET_NAME }}/

      - name: Code Deploy
        run: aws deploy create-deployment --application-name LingoTalk
          --deployment-group-name prod
          --s3-location bucket=${{ env.BUCKET_NAME }},bundleType=zip,key=build.zip
